name: Labeler
on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4  
        with:
          node-version: 20
          token: ${{ secrets.SECRET_ACTIONS_PORTIFOLIO_EXEMPLE }}
