name: Labeler
on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.SECRET_ACTIONS_PORTIFOLIO_EXEMPLE }}"